### PR TITLE
coinstring: use createHash directly

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by jprichardson** [comment]
Meh. I'm not sure about this. What's the payload on including full crypto? Is it really a big deal if using something like Google Closure compiler (remove unused JS)?

**Comment by dcousens** [comment]
The payload is some 300k in a typical browserify build.

**Comment by dcousens** [comment]
For what its worth,  in my builds,  the closure compiler was not able to remove the unused JS associated with this.

**Comment by jprichardson** [comment]
Okay, so if a person is going to be concerned about payload size, why not just go all of the way and use `sha256` and `ripemd160` algorithms directly since `createHash` pulls in unnecessary hashes?

**Comment by dcousens** [comment]
@jprichardson because they don't exist as separate packages?   Maybe that is something we should fix upstream.

I think  `sha256 = require('sha256')` would be great,  where the `sha256` module pulls in the common code that exists in `createHash` rather than the other way round.

But,  that requires a bit more work,  for a much smaller pay off compared to what we can get right now with this change.

No doubt, that is more ideal though.

**Comment by jprichardson** [comment]
> because they don't exist as separate packages? 

Umm.... 

- https://www.npmjs.com/package/sha256
- https://www.npmjs.com/package/ripemd160

They've existed for 1.5 years :p

**Comment by dcousens** [comment]
@jprichardson but not using the same **streamable** API.   We can definitely change that though.

**Comment by dcousens** [comment]
@jprichardson good to merge

**Comment by dcousens** [comment]
Rebased.  Sorry about the mess around @jprichardson.

**Comment by dcousens** [comment]
@jprichardson the tests are passing, coveralls is dying for some unknown reason though.

**Comment by jprichardson** [comment]
Alright dude, published.

**Pull request merged**
